userInfo:
  avatar: ''
  userName: '马春辉'
  qualifications: '华北理工大学轻工学院 | 本科'
  email: '2420228300@qq.com'
  phone: '15127389176'
  birthday: '2001-02-01'
  description: '过去无可挽回，未来可以改变'
  account:
    - name: 'Github'
      icon: 'github'
      url: 'https://github.com/hui3215'
    - name: 'Gitee'
      icon: 'gitee'
      url: 'https://gitee.com/MchBlog'
    - name: 'WeChat'
      icon: 'wechat'
      copy: '15127389176'
    - name: 'QQ'
      icon: 'qq'
      copy: '2420228300'
  skills:
    - skill: 'Java'
      percentage: 80
    - skill: '.NET'
      percentage: 60
    - skill: 'Spring Booot'
      percentage: 85
    - skill: 'Spring Cloud'
      percentage: 30
    - skill: 'Vue'
      percentage: 82
    - skill: 'Linux'
      percentage: 60
  skillCustomColors:
    - color: '#f56c6c'
      percentage: 20
    - color: '#e6a23c'
      percentage: 40
    - color: '#5cb87a'
      percentage: 60
    - color: '#1989fa'
      percentage: 80
    - color: '#6f7ad3'
      percentage: 100
  experiences:
    - content: '河北科技工程职业技术大学'
      timestamp: '2019-09-10 12:00'
      size: 'large'
      type: 'primary'
    - content: '移动应用开发大赛'
      timestamp: '2020-06-06 07:00'
      color: '#0bbd87'
    - content: '河北省商务软件开发大赛'
      timestamp: '2023-06-06 07:00'
      size: 'large'
    - content: '商务软件开发国赛'
      timestamp: '2023-09-08 06:00'
      hollow: true
      type: 'primary'
    - content: '华北理工大学轻功学院'
      timestamp: '2023-9-11 20:46'
      color: '#ff0081'
  projectsInfo:
    - name: '个人主页'
      url: 'https://github.com/hui3215/hui-homepage.git'
      skills:
        - Vue
      description: '让人快速了解你会什么，有什么事迹的个人主页'
    - name: '河图洛书'
      url: 'https://gitee.com/MchBlog/map-system-manager.git'
      skills:
        - Vue
        - Spring Boot
      description: '一款前后端分离的图纸管理系统，注重安全，开发了一套基于国密M2的河图洛书的加密解密的方式'
  introduction:
    content: '我毕业于XXX大学，计算机科学与技术专业。在校期间，我认真学习了计算机科学基础知识，并对Java编程语言产生了浓厚的兴趣。我积极参加各种编程比赛和项目开发，积累了丰富的实践经验.我对Java编程语言有着深入的理解，并掌握了Spring、Spring Boot、MyBatis等主流框架。我熟悉Linux操作系统，并有一定的数据库管理经验我热爱编程工作，有着强烈的学习能力和责任感。'
    keywords:
      - Spring
      - Spring Boot
      - MyBatis
      - Linux
      - Java
website:
  title: SpringHui
  ICPRecordNumber: xxxxxxxxx
  backgroundWords:
    - Java
    - Spring
    - SpringBoot
    - SpringCloud
    - Rabbit
    - Nacos
    - ES
    - Netty
    - Mysql
    - Redis
    - Vue
    - Html
    - CSS
    - JS
    - .NET
    - WPF
    - ASP
  backgroundColor: #222
  backgroundItemInfoBorderColor: #22d3ee
  cardInfo:
    # default
    # 神秘紫蓝渐变 mystic-violet-blue-gradient
    # 天空蓝渐变 sky-blue-gradient
    # 瑰丽紫红渐变 magnificent-purple-red-gradient
    # 温暖阳光渐变 warm-sunlight-gradient
    # 自然绿意渐变 natural-greenery-gradients
    theme: sky-blue-gradient
    borderWidth: 4px
    borderRadius: 16px

